# Generated by Django 2.2.5 on 2020-09-09 00:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokedexModelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(blank=True)),
                ('ability', models.CharField(max_length=255, null=True)),
                ('weaknesses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), size=None)),
                ('imagePath', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonModelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('trainer_region', models.CharField(max_length=255, null=True)),
                ('birth_year', models.DateField()),
                ('pokedexData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex', to='Api.PokedexModelData')),
            ],
        ),
    ]
